### ISSUE TITLE
Mailserver Probleme

### ISSUE THREAD

**Issue by MOuli90** [OpenAdaptronik/Rattler#83]
Obwohl der MX-DNS Eintrag da ist, werden vom Server aus immer noch jegliche Mails blockiert. Es soll geprüft werden, bei welchen Mail Systemen welche "Antworten" zurück kommen.

**Comment by MOuli90** [comment]
@Maren4 Gab es hierzu schon weiteren Feedback vom LBF?

**Comment by GeorgStoll** [comment]
From PM side this is considered the most urgent issue at current time.

**Comment by Huy-DC** [comment]
I'll look what I can do about it.
